【CHG】CI

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,13 +2,36 @@
 # * http://www.objc.io/issue-6/travis-ci.html
 # * https://github.com/supermarin/xcpretty#usage
 
-osx_image: xcode7.3
+osx_image: xcode9
 language: objective-c
-# cache: cocoapods
-# podfile: Example/Podfile
-# before_install:
-# - gem install cocoapods # Since Travis is not always on latest version
-# - pod install --project-directory=Example
+
+cache: cocoapods
+podfile: Example/Podfile
+
+before_install:
+- gem install cocoapods # Since Travis is not always on latest version
+- pod install --project-directory=Example
+
+workspace_name() {
+workspace_file=`find . -maxdepth 2 -name *.xcworkspace -exec basename {} \;`
+echo ${workspace_file%.xcworkspace}
+
+workspace=$(workspace_name)
+
+check_result() {
+  if [ $? != 0 ]; then
+  echo "$1 failed!!"
+  echo "$?"
+  exit 1
+  else
+  echo "$1 passed."
+  echo "$?"
+  fi
+}
+
 script:
-- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/PopoverObjC.xcworkspace -scheme PopoverObjC-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
-- pod lib lint
+- set -o pipefail
+- xcodebuild -workspace Example/$workspace.xcworkspace -scheme $workspace-Example -destination 'platform=iOS Simulator,OS=11.0,name=iPhone 7' test
+- pod lib lint --allow-warnings --verbose
+
+}
